
PROXY_URL: "http://192.168.54.92:9695"

# EVAL_MODEL: "lmsys/vicuna-33b-v1.3"
EVAL_LM_MODEL: "Llama-2-7b-hf"
EVAL_QW_MODEL: "Qwen1.5-7B-Chat"
# EVAL_PROXY_MODEL: "gpt-4o-mini"
EVAL_PROXY_MODEL: "gpt-4"

mission: "DESCTION THE FEELING"
# dataset: &dataset "SSVTP"
# dataset: &dataset "HCT"
dataset: &dataset "TVL"

Model:

  name: KNN
  args:
    rebuild: False
    queryKeyType: "VT"
    queryNum: 5
    resultNum: 4
    dataset: *dataset

  # name: SyncVote
  # args:
  #   rebuild: False
  #   queryKeyType: "VT"
  #   queryNum: [5,5]
  #   resultNum: 4
  #   dataset: *dataset 

  # name: DualVote
  # args:
  #   rebuild: False
  #   queryKeyType: "VT"
  #   queryNum: [5,5]
  #   resultNum: 4
  #   dataset: *dataset 

  # name: WeightVote
  # args:
  #   rebuild: False
  #   queryKeyType: "VT"
  #   queryNum: [5,5]
  #   resultNum: 4
  #   dataset: *dataset 

  # name: TVL-S

  # name: GPT4V

  # args:
  #   rebuild: False
  #   queryKeyType: "VT"
  #   queryNum: [5,5]
  #   resultNum: 4